#!/bin/bash
# ================================================================
# GPS SaaS Platform — BULLETPROOF Setup Script v5
# ✅ NEVER modifies docker-compose.yml (was causing YAML corruption)
# ✅ Deletes ALL .env files first (no merge conflicts ever)
# ✅ Generates fresh secrets with exact variable names backend needs
# ✅ Removes all old containers, volumes, images, node_modules
# ✅ Forces clean Docker build every time
# ================================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

step()  { echo -e "\n${CYAN}${BOLD}[→]${NC} $1"; }
ok()    { echo -e "${GREEN}[✔]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
fail()  { echo -e "\n${RED}${BOLD}[✘] FATAL: $1${NC}\n"; exit 1; }

echo ""
echo -e "${BOLD}${BLUE}"
echo "╔══════════════════════════════════════════════════════╗"
echo "║     GPS SaaS Platform — Bulletproof Setup v5         ║"
echo "║     Clean slate • Fresh secrets • No YAML errors     ║"
echo "╚══════════════════════════════════════════════════════╝"
echo -e "${NC}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"
ok "Working directory: $SCRIPT_DIR"

# ── 1. PREREQUISITES ─────────────────────────────────────────────
step "Checking prerequisites..."
command -v docker  >/dev/null 2>&1 || fail "Docker not found. Run: curl -fsSL https://get.docker.com | sh"
command -v openssl >/dev/null 2>&1 || fail "openssl not found. Run: sudo apt install openssl"

if command -v docker-compose >/dev/null 2>&1; then
    DC="docker-compose"
elif docker compose version >/dev/null 2>&1; then
    DC="docker compose"
else
    fail "Docker Compose not found. Run: sudo apt-get install -y docker-compose-plugin"
fi
ok "Docker  : $(docker --version | cut -d' ' -f3 | tr -d ',')"
ok "Compose : $($DC version --short 2>/dev/null || echo 'detected')"

# ── 2. RESTORE docker-compose.yml FROM GIT IF CORRUPTED ──────────
step "Verifying docker-compose.yml integrity..."

# Check if YAML is valid
if ! python3 -c "import yaml; yaml.safe_load(open('docker-compose.yml'))" 2>/dev/null; then
    warn "docker-compose.yml is corrupted! Restoring from git..."
    if git diff --name-only HEAD 2>/dev/null | grep -q "docker-compose.yml"; then
        git checkout HEAD -- docker-compose.yml 2>/dev/null && ok "Restored from git" || true
    fi
    # If still broken, try the backup
    if [ -f docker-compose.yml.bak ]; then
        cp docker-compose.yml.bak docker-compose.yml
        ok "Restored from backup"
    fi
    # Final check
    python3 -c "import yaml; yaml.safe_load(open('docker-compose.yml'))" 2>/dev/null \
        || fail "docker-compose.yml is still corrupted. Please re-download the project."
fi
ok "docker-compose.yml is valid"

# Make a backup before we do anything
cp docker-compose.yml docker-compose.yml.bak
ok "docker-compose.yml backed up"

# ── 3. NUKE ALL OLD .ENV FILES ────────────────────────────────────
step "Removing ALL .env files (prevents merge conflict errors)..."

for f in .env .env.production .env.local .env.development .env.staging \
          .env.test .env.backup .env.bak .env.old .env.example \
          .env.sample .env.template .env.prod .env.copy; do
    [ -f "$f" ] && rm -f "$f" && warn "Deleted: $f" || true
done

# Kill any file with git merge conflict markers
find . -maxdepth 3 -name ".env*" -type f 2>/dev/null | while IFS= read -r f; do
    grep -q "<<<<<<\|=======\|>>>>>>>" "$f" 2>/dev/null && rm -f "$f" && warn "Deleted conflict file: $f" || true
done

ok "All .env files removed"

# ── 4. GENERATE FRESH SECRETS ─────────────────────────────────────
step "Generating cryptographic secrets..."

JWT_SECRET=$(openssl rand -hex 32)
JWT_REFRESH_SECRET=$(openssl rand -hex 32)
DB_PASSWORD=$(openssl rand -hex 16)
REDIS_PASSWORD=$(openssl rand -hex 12)
SESSION_SECRET=$(openssl rand -hex 24)

ok "Secrets generated"

# ── 5. WRITE CLEAN .env.production ───────────────────────────────
# Variable names match EXACTLY what backend/src/server.js checks:
# POSTGRES_HOST, POSTGRES_PORT, POSTGRES_DB, POSTGRES_USER,
# POSTGRES_PASSWORD, JWT_SECRET, JWT_REFRESH_SECRET
step "Writing .env.production..."

cat > .env.production << ENVEOF
# ================================================================
# GPS SaaS Platform — Auto-generated by setup.sh on $(date)
# DO NOT EDIT — re-run setup.sh to regenerate
# ================================================================

# Node
NODE_ENV=production
API_PORT=3000
LOG_LEVEL=info

# PostgreSQL — exact names required by backend/src/server.js
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=gpsdb
POSTGRES_USER=gpsuser
POSTGRES_PASSWORD=${DB_PASSWORD}
DATABASE_URL=postgresql://gpsuser:${DB_PASSWORD}@postgres:5432/gpsdb

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

# JWT — exact names required by backend/src/server.js
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=7d
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
REFRESH_EXPIRES_IN=30d

# Session
SESSION_SECRET=${SESSION_SECRET}

# TCP
TCP_PORT=5000

# CORS
CORS_ORIGIN=*

# Admin (change after first login)
ADMIN_EMAIL=admin@gps.local
ADMIN_PASSWORD=Admin@123!

# Email (optional — leave blank to disable)
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=noreply@gpstracker.com

# Razorpay (optional — leave blank to disable)
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=
ENVEOF

ok ".env.production written"

# Symlink .env → .env.production
ln -sf .env.production .env
ok ".env → .env.production"

# Protect .env files from git forever
{
  grep -qxF ".env"            .gitignore 2>/dev/null || echo ".env"
  grep -qxF ".env.*"          .gitignore 2>/dev/null || echo ".env.*"
  grep -qxF "DEPLOYMENT_INFO.txt" .gitignore 2>/dev/null || echo "DEPLOYMENT_INFO.txt"
} >> .gitignore 2>/dev/null || true
ok ".gitignore updated"

# ── 6. FIX docker-compose.yml (SAFELY — only env_file lines) ─────
step "Fixing docker-compose.yml env_file references (safe edit only)..."

# ONLY fix env_file: .env lines → env_file: .env.production
# Use sed on specific pattern — does NOT touch Redis command block
sed -i \
    -e 's|^\( *env_file: *\)\.env$|\1.env.production|g' \
    -e 's|^\( *env_file: *\)\- \.env$|\1.env.production|g' \
    docker-compose.yml 2>/dev/null && ok "env_file references updated" || warn "sed skipped"

# Validate YAML is still good after our edit
python3 -c "import yaml; yaml.safe_load(open('docker-compose.yml'))" 2>/dev/null \
    && ok "docker-compose.yml still valid after edit" \
    || { warn "Edit broke YAML — restoring backup"; cp docker-compose.yml.bak docker-compose.yml; }

# ── 7. STOP + REMOVE ALL OLD CONTAINERS & VOLUMES ────────────────
step "Removing all old containers, volumes, networks..."

$DC down --remove-orphans --volumes 2>/dev/null && ok "Old stack removed" || warn "Nothing was running"

for c in gps_postgres gps_redis gps_backend gps_tcp_server \
          gps_notifications gps_frontend gps_admin gps_nginx; do
    docker rm -f "$c" 2>/dev/null && warn "Removed: $c" || true
done
ok "Old containers gone"

# ── 8. REMOVE OLD IMAGES & BUILD CACHE ───────────────────────────
step "Cleaning old Docker images and build cache..."

PROJECT=$(basename "$SCRIPT_DIR" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9')
for p in "$PROJECT" "gps-saas" "gpssaas" "gps_backend" "gps_frontend" "gps_admin"; do
    docker images --format '{{.Repository}}:{{.Tag}}' 2>/dev/null \
        | grep -i "$p" \
        | xargs -r docker rmi -f 2>/dev/null || true
done

docker image prune  -f >/dev/null 2>&1 && ok "Dangling images pruned"
docker builder prune -f >/dev/null 2>&1 && ok "Build cache cleared"

# ── 9. REMOVE node_modules & LOCK FILES ──────────────────────────
step "Removing node_modules and lock files..."
find . -name "node_modules" -type d -prune -exec rm -rf {} + 2>/dev/null || true
find . \( -name "package-lock.json" -o -name "yarn.lock" \) -delete 2>/dev/null || true
ok "node_modules removed"

# ── 10. PIN PACKAGE.JSON TO LATEST STABLE ────────────────────────
step "Updating package.json files..."

cat > backend/package.json << 'EOF'
{
  "name": "gps-backend",
  "version": "2.0.0",
  "main": "src/server.js",
  "scripts": {
    "start": "node src/server.js",
    "dev": "nodemon src/server.js"
  },
  "dependencies": {
    "bcrypt":                 "^5.1.1",
    "bcryptjs":               "^2.4.3",
    "compression":            "^1.7.4",
    "cors":                   "^2.8.5",
    "dotenv":                 "^16.4.5",
    "express":                "^4.19.2",
    "express-mongo-sanitize": "^2.2.0",
    "express-rate-limit":     "^7.3.1",
    "helmet":                 "^7.1.0",
    "ioredis":                "^5.4.1",
    "joi":                    "^17.13.3",
    "jsonwebtoken":           "^9.0.2",
    "morgan":                 "^1.10.0",
    "pdfkit":                 "^0.15.0",
    "pg":                     "^8.12.0",
    "pg-hstore":              "^2.3.4",
    "prom-client":            "^15.1.3",
    "razorpay":               "^2.9.5",
    "sequelize":              "^6.37.3",
    "socket.io":              "^4.7.5",
    "uuid":                   "^10.0.0",
    "winston":                "^3.13.0"
  },
  "devDependencies": { "nodemon": "^3.1.4" }
}
EOF
ok "backend/package.json updated"

cat > tcp-server/package.json << 'EOF'
{
  "name": "gps-tcp-server",
  "version": "2.0.0",
  "main": "src/server.js",
  "scripts": { "start": "node src/server.js" },
  "dependencies": {
    "dotenv":  "^16.4.5",
    "ioredis": "^5.4.1",
    "pg":      "^8.12.0"
  }
}
EOF
ok "tcp-server/package.json updated"

[ -f notifications/package.json ] && cat > notifications/package.json << 'EOF'
{
  "name": "gps-notifications",
  "version": "2.0.0",
  "main": "worker.js",
  "scripts": { "start": "node worker.js" },
  "dependencies": {
    "dotenv":     "^16.4.5",
    "ioredis":    "^5.4.1",
    "nodemailer": "^6.9.14"
  }
}
EOF
[ -f notifications/package.json ] && ok "notifications/package.json updated"

# ── 11. UPDATE DOCKERFILES ────────────────────────────────────────
step "Updating Dockerfiles..."

cat > backend/Dockerfile << 'EOF'
FROM node:20-alpine
RUN apk add --no-cache curl wget python3 make g++
WORKDIR /app
COPY package.json ./
RUN rm -f package-lock.json yarn.lock && \
    npm install --production --no-fund --no-audit
COPY . .
RUN mkdir -p logs invoices
EXPOSE 3000
HEALTHCHECK --interval=20s --timeout=10s --start-period=120s --retries=6 \
  CMD wget -qO- http://localhost:3000/health | grep -q '"status"' || exit 1
CMD ["node", "src/server.js"]
EOF
ok "backend/Dockerfile updated"

cat > tcp-server/Dockerfile << 'EOF'
FROM node:20-alpine
RUN apk add --no-cache curl
WORKDIR /app
COPY package.json ./
RUN rm -f package-lock.json yarn.lock && \
    npm install --production --no-fund --no-audit
COPY . .
EXPOSE 5000
CMD ["node", "src/server.js"]
EOF
ok "tcp-server/Dockerfile updated"

[ -f notifications/Dockerfile ] && cat > notifications/Dockerfile << 'EOF'
FROM node:20-alpine
WORKDIR /app
COPY package.json ./
RUN rm -f package-lock.json yarn.lock && \
    npm install --production --no-fund --no-audit
COPY . .
CMD ["node", "worker.js"]
EOF
[ -f notifications/Dockerfile ] && ok "notifications/Dockerfile updated"

# ── 12. DIRECTORIES & SSL CERT ───────────────────────────────────
step "Creating directories and SSL certificate..."
mkdir -p nginx/ssl logs backend/logs 2>/dev/null || true

if [ ! -f nginx/ssl/nginx.crt ]; then
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout nginx/ssl/nginx.key \
        -out    nginx/ssl/nginx.crt \
        -subj "/C=IN/ST=MH/L=Mumbai/O=GPS/CN=localhost" 2>/dev/null
    ok "Self-signed SSL cert created"
else
    ok "SSL cert exists"
fi

# ── 13. BUILD DOCKER IMAGES ───────────────────────────────────────
step "Building Docker images (no-cache — takes 5-10 min first time)..."
echo ""

$DC --env-file .env.production build --no-cache 2>&1 | \
    grep -E "^(Step|step|STEP|Successfully|ERROR|error:|Warning|--->" || true

echo ""
ok "Build complete"

# ── 14. START SERVICES ────────────────────────────────────────────
step "Starting all services..."
$DC --env-file .env.production up -d
ok "Services started"

# ── 15. WAIT FOR POSTGRESQL ───────────────────────────────────────
step "Waiting for PostgreSQL..."
MAX=60; N=0
until $DC exec -T postgres pg_isready -U gpsuser -d gpsdb >/dev/null 2>&1; do
    N=$((N+1))
    [ $N -ge $MAX ] && fail "PostgreSQL not ready after $((MAX*3))s\nCheck: $DC logs postgres"
    printf "."; sleep 3
done
echo ""; ok "PostgreSQL ready"

# ── 16. WAIT FOR BACKEND ──────────────────────────────────────────
step "Waiting for Backend API..."
MAX=40; N=0
until curl -sf http://localhost:3000/health >/dev/null 2>&1; do
    N=$((N+1))
    if [ $N -ge $MAX ]; then
        warn "Backend timed out — showing logs:"
        $DC logs --tail=40 backend 2>/dev/null || true
        break
    fi
    printf "."; sleep 4
done
echo ""
curl -sf http://localhost:3000/health >/dev/null 2>&1 && ok "Backend API healthy" || warn "Backend still starting (check: $DC logs backend)"

# ── 17. SET ADMIN PASSWORD ────────────────────────────────────────
step "Setting admin password..."
sleep 2

$DC exec -T backend node - << 'JSEOF' 2>/dev/null \
    && ok "Admin password set → Admin@123!" \
    || warn "Admin password skipped (non-fatal — may already be set)"
const bcrypt = require('bcryptjs');
const { Sequelize } = require('sequelize');
const seq = new Sequelize(process.env.DATABASE_URL, { logging: false });
(async () => {
  try {
    await seq.authenticate();
    const hash = await bcrypt.hash('Admin@123!', 12);
    await seq.query(
      "UPDATE users SET password=:h WHERE email IN ('admin@gps.local','superadmin@gps.local')",
      { replacements: { h: hash } }
    );
    console.log('Done');
    await seq.close();
  } catch(e) { console.log('Note:', e.message); process.exit(0); }
})();
JSEOF

# ── 18. STATUS ────────────────────────────────────────────────────
step "Service status:"
echo ""
$DC ps 2>/dev/null || true

# ── 19. SAVE DEPLOYMENT INFO ──────────────────────────────────────
PUBLIC_IP=$(curl -sf --max-time 5 https://api.ipify.org 2>/dev/null || \
            curl -sf --max-time 5 http://checkip.amazonaws.com 2>/dev/null || \
            hostname -I 2>/dev/null | awk '{print $1}' || \
            echo "YOUR_SERVER_IP")

cat > DEPLOYMENT_INFO.txt << INFOEOF
================================================================
GPS SaaS Platform — Deployment Info
Generated: $(date)
================================================================

URLs:
  Client Portal  : http://${PUBLIC_IP}
  Admin Panel    : http://${PUBLIC_IP}/admin
  Backend API    : http://${PUBLIC_IP}/api
  Health Check   : http://${PUBLIC_IP}/api/health
  GPS TCP Port   : ${PUBLIC_IP}:5000

Login:
  Email    : admin@gps.local
  Password : Admin@123!

Database:
  DB       : gpsdb
  User     : gpsuser
  Password : ${DB_PASSWORD}

Redis Password   : ${REDIS_PASSWORD}
JWT_SECRET       : ${JWT_SECRET}
JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

Commands:
  Logs    : $DC logs -f [service]
  Restart : $DC restart [service]
  Stop    : $DC down
  Rebuild : sudo bash setup.sh
================================================================
INFOEOF
ok "Credentials saved → DEPLOYMENT_INFO.txt"

# ── DONE ──────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}"
echo "╔══════════════════════════════════════════════════════╗"
echo "║   ✅  GPS SaaS Platform — SETUP COMPLETE!            ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║                                                      ║"
printf "║   🌐 Portal  → http://%-29s║\n" "${PUBLIC_IP}"
printf "║   🔧 Admin   → http://%-29s║\n" "${PUBLIC_IP}/admin"
printf "║   📡 API     → http://%-29s║\n" "${PUBLIC_IP}/api"
printf "║   🛰️  TCP     → %-34s║\n" "${PUBLIC_IP}:5000"
echo "║                                                      ║"
echo "║   👤 admin@gps.local  /  Admin@123!                  ║"
echo "║                                                      ║"
echo "║   📋 cat DEPLOYMENT_INFO.txt   (all passwords)       ║"
echo "║   📊 $DC logs -f          (live logs)           ║"
echo "║                                                      ║"
echo "║   🧪 Test without hardware:                          ║"
echo "║      Login → Admin Panel → Device Tester             ║"
echo "╚══════════════════════════════════════════════════════╝"
echo -e "${NC}"
