apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: gps-saas
type: Opaque
stringData:
  JWT_SECRET: supersecret
  JWT_REFRESH_SECRET: refreshsecret
  DB_PASSWORD: postgres
  REDIS_HOST: redis